# .streamlit/secrets.toml (Contenu à copier)
[gcp_service_account]
type = "service_account"
project_id = "lacroixglorieuse"
private_key_id = "a6eef6cf959efc514aecb13d254f479c49fa5c72"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDGS3Is8epPd9WP
lIG2drBuPbuhcu01vLATsQxZpKZFslqx7KzGReh7DTsz/r4S6S9OK04IMlJjf80Z
QLa/6s7FRndqD8JxOkUyDaL4ROumWKbntRSVmKtxECCAh5ghIcm5Gu8877RG8gOL
HesIIUcwIlLyb5487ZdrnYsrdQQqZn15kwuebCHKqwvqweeQvm3WFCd9fvcdoUEY
gbt2UuBdywDpUxWY1zOzAkeC3sldmM5GnJ68EYiMnqUjoiqjwslfvjQpR97ZGfRZ
Pft2GHesXrk+eQaAqarZDyZ7iz8hmnZsJci54y2XzX+46RuTPZv3WSY9mqZVJJ5m
HdRQuVenAgMBAAECggEAMQWx4l6kOKU9jNOABeXt1DM60b0h26kcNqIMlZTY7l4b
geUrCZF62gD5Y+9UekRfx4l5LxmRuLt9rwKKq4OXProfB3+B6JApTyiD47DWOTet
e5cO0bT+nWMJRf0/pOE/h52bC4uPHAL00U3CLy5a9RFnRDxH+HQcfSRjpYi2UOy6
JUD8lcLKCSjGJg0d51GkKm7q5KY+jQo6o6tJDi9QKmmrpkJriGFwhz/SVstb4w+n
kiVqM5FWahTPmNQJutncmoLwEwy/pOSxv8LI1XuyBxQchHMspD5LlXwlMNGq1YVB
HLE7FHFmDBMIeBq9LRrmZRe9QDbmp1EviCWrddOP0QKBgQDmx7YKi2+eDQ2Pcv8N
Qdqj2ZTajQlzPYNItsC++RhSxB/1co7nvTPRbGQ4aBzmOqqEELttnen9O0LtlvYk
vjjh/XjciV078VmWrbRJTqpJTQm0XyQVdlHccSI53sd6uXwR54+5sr6kUnTZjX5Q
R5N0wUnQ+FvXy4aEgSDicBjkFQKBgQDb9uze1qNnJH7QAgb8PaSQQAL2CxSrrCcT
j3M8fVlr+yjxPHYYpBmOsi6Lomzmu3nsxPQdio2lvtYk/VXeqmtq3rD/bSb7vc++
1ghoG8r4MiwJ84ecxQbxI5OkAnF7zOSdr15ZhEZ3zchRjj8Bpt0yXc/XV1GYfxC8
fgtkiLJPywKBgEgKS69a+4rQ9Ey1TxzqU8AWKbtXj32j1Bmcwupag9dCVd+e1TFO
BKD5PwfEqFDOO3BicL+1LdfY6fmUyF2L6+HP6CyfzLTrkFXS/5ZqsgmTvNXLZU41
0zQHNPHvs0GCKVLFgD4tqAlPnB5VZvrUfRlTRSGwhasFY4Z1cLh+2aZJAoGAUU3U
AAoWG+nBdeFJ87JVQXxnm8o8ubfIOdKsJY+vndoYKBLRFAqT58q0qag/2IkzZ/Dk
yoaMFNeVD9cUBlm3mqj1g3Q1FJf0UfWK5fBf9Z2V6Ze6aJfrGPate9HrYHc7iY1o
sm3SHjZR9NM/Nr0WxacnS9Fat6M/7Gwqid59CkECgYEAxFaWR2DDx/bUdELmjAdI
fIUl+Hh/L481pfP7+as9FRPEoVMrg8rSoXGgtxXYP4pUo4MXK6R3uDsCutXkjNO6
pRdwIxT9BXUY8tuIQKltWR+fOzpoCxYruqncnKz7Tcon1tm2rOpT8TTCnHNzuieo
Z8UJM6jeLacElMfz+/AAgp8=
-----END PRIVATE KEY-----
"""
client_email = "streamlit-lacroix-reader@lacroixglorieuse.iam.gserviceaccount.com"
client_id = "111826608201469628499"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-lacroix-reader%40lacroixglorieuse.iam.gserviceaccount.com"
universe_domain = "googleapis.com" 

# Secret de sécurité pour le hachage des mots de passe
SALT_PASSWORD = "Une_phrase_tres_longue_et_secrete_pour_le_projet_LaCroixglorieuse"
